[project]
name = "seml"
version = "0.4.0"
description = "Slurm Experiment Management Library"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "Daniel Zügner", email = "zuegnerd@in.tum.de"},
    {name = "Johannes Gsteiger", email = "johannes.gasteiger@tum.de"},
    {name = "Nicholas Gao", email = "n.gao@tum.de"},
    {name = "Dominik Fuchsgruber", email = "d.fuchsgruber@tum.de"},
    {name = "DAML Group @ TUM"}
]
maintainers = [
    {name = "Nicholas Gao", email = "n.gao@tum.de"},
    {name = "Dominik Fuchsgruber", email = "d.fuchsgruber@tum.de"},
]
classifiers = [
    "Programming Language :: Python"
]

dependencies = [
    "numpy>=1.15",
    "pymongo>=3.11",
    "pandas",
    "sacred @ git+https://github.com/IDSIA/sacred.git@17c530660d5b405af0f5c286b1a93f3d8911d026#egg=sacred",
    "pyyaml>=5.1",
    "jsonpickle>=2.2",
    "munch>=2.0.4",
    "tqdm>=4.36",
    "debugpy>=1.2.1",
    "requests>=2.28.1",
    "typer>=0.9, <1.0",
    "rich>=13.0, <14.0",
    "omegaconf>=2.3.0, <3.0",
]

[project.urls]
Homepage = "https://github.com/TUM-DAML/seml"
Documentation = "https://github.com/TUM-DAML/seml/blob/master/docs.md"
Repository = "https://github.com/TUM-DAML/seml"
Changelog = "https://github.com/TUM-DAML/seml/releases/latest"

[project.scripts]
seml = "seml.__main__:main"
